---
- hosts: localhost
  gather_facts: no
  serial: 1
  tasks:
    - uri:
        #url: "https://{{ publicEndpoint }}:{{ serverPortHttps }}"
        url: "https://finanweb.xxxxtest.es:1444"
        return_content: yes
        status_code: 200, 401, 403
        validate_certs: no
        use_proxy: no
      retries: 2 
      delay: 2
      register: result_public
      until: result_public is not failed
      delegate_to: localhost
    - debug: var=result_public
    