bpmf:
  hosts:
    server1: 
      ansible_host: 172.31.15.5
      ansible_user: spacanar
      ansible_ssh_private_key_file: spacanar-canary
  vars: 
    artifact_name: front-package
    artifact: front-package.tgz
    local_rsync_dir: /tmp/bpmf
    remote_dir: /home/spacanar/spaweb/
    upload_sourcemaps: false
banca_telefonica:
  hosts:
    server_bt1: 
      ansible_host: 172.31.15.5
      ansible_user: spaint
      ansible_ssh_private_key_file: spaint_canary
  vars: 
    artifact_name: banca-telefonica
    artifact: banca-telefonica.tgz
    local_rsync_dir: /tmp/bt
    remote_dir: /home/spaint/spaweb/
    upload_sourcemaps: false  