bpmf:
  hosts:
    server1: 
      ansible_host:  172.17.242.204
      ansible_user: nacho
      ansible_password: nacho
    server2:
      ansible_host:  172.17.242.204
      ansible_user: nacho
      ansible_password: nacho
  vars:
    remote_dir: /mnt/c/devhost/spauser/web01pru/
    artifact: BPMF-banca-privada-mfe.tgz
    artifact_name: BPMF-banca-privada-mfe.tgz
    upload_sourcemaps: false
    sourcemaps_ext: js.uni.map
    app_base_url: https://locahost/test
    apm_server_url: https://nacho.test/kibana_pre/api/apm/sourcemaps
    apm_service: univia-desa
    apm_service_version: "1.0"
    apm_apikey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          12323445556777
