---
- become: true
  block:
  - name: Creando carpeta temporal para el trustore
    tempfile:
      path: "/tmp/"
      prefix: "trustore{{ lookup('env','BUILD_TAG') }}_"
      state: directory
    register: tempfoldertrust
  - name: Uploading CAs
    copy:
      src: "trust/{{ entorno }}/"
      dest: "{{ tempfoldertrust.path }}"
      backup: yes
  - name: Detectando CAs a instalar
    find:
      paths: "{{ tempfoldertrust.path }}"
    register: ca_files
  - name: Creando carpeta temporal para el certificado
    tempfile:
      path: "/tmp/"
      prefix: "keystore_{{ lookup('env','BUILD_TAG') }}_"
      state: directory
    register: tempfolder
  - name: Uploading Cert
    copy:
      content: "{{ keystore_content | b64decode }}"
      dest: "{{ tempfolder.path }}/cert"
      backup: yes
  - name: Comprobando si existe kdb
    stat:
      path: "{{ http.keyfile }}"
    register: kdbResult
  - name: Creando Kdb
    command: "/usr/IBM/HTTPServer9/bin/gskcapicmd -keydb -create -db {{ http.keyfile }} -type kdb -stash -pw {{ keystore_password }} -empty"
    when: not kdbResult.stat.exists    
  - name: Añadiendo CAS
    command: "/usr/IBM/HTTPServer9/bin/gskcapicmd -cert -import -file {{ item.path }} -target {{ http.keyfile }}  -pw {{ trustore_password }} -type pkcs12 -stashed" 
    loop: "{{ ca_files.files }}"
  - name: Añadiendo Certificados
    #command: "/usr/IBM/HTTPServer9/bin/gskcapicmd -cert -add -file {{ tempfolder.path }}/cert -db {{ http.keyfile }} -stashed -label {{ publicEndpoint }}"
    command: "/usr/IBM/HTTPServer9/bin/gskcapicmd -cert -import -file {{ tempfolder.path }}/cert -target {{ http.keyfile }}  -pw {{ keystore_password }} -type pkcs12 -stashed"
  always:
    - name: "Removing temporary files generated by {{ appName }}"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ tempfolder.path }}"
        - "{{ tempfoldertrust.path }}"