---
appserver:
  hosts:
    bwebspre1:
      ansible_host: 172.31.10.9
      #ansible_user: "{{ lookup('env','ansibleUser') }}"
      #ansible_password: "{{ lookup('env','ansiblePassword') }}"
      ansible_user: "spauser2"
      ansible_ssh_private_key_file: "spauser2-pre"
      ip_vhost: 172.31.10.15
      f5_member_name: bwebspre1.finanwebrm
    bwebspre2:
      ansible_host: 172.31.10.10
      #ansible_user: "{{ lookup('env','ansibleUser') }}"
      #ansible_password: "{{ lookup('env','ansiblePassword') }}"
      ansible_user: "spauser2"
      ansible_ssh_private_key_file: "spauser2-pre"
      ip_vhost: 172.31.10.18
      f5_member_name: bwebspre2.finanwebrm
  vars:
      remote_dir: "/home/spauser2/finanwebrmpre.xxxxtest.es/"
      artifact: "FARM-finanweb-rm.tgz"
      artifact_name: "FARM-finanweb-rm.tgz"
      upload_sourcemaps: "{{ sourceMap|bool }}"
      publicEndpoint: finanwebrmpre.xxxxtest.es
      publicHttpsPort: 443
      hasBalancer: true
lb:
  hosts:
    lb-f5-prep:
      ansible_host: 195.76.110.92
  vars:
      pool: pre.finanwebRM_443
      partition: finanweb-RM-PRE